
name: .NET 8 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      # Смени пътя към твоя .sln или .csproj файл
      run: dotnet restore StorySpoiler/StorySpoiler.sln

    - name: Build
      run: dotnet build StorySpoiler/StorySpoiler.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test StorySpoiler/StorySpoiler.sln --no-build --verbosity normal
